spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/basket
    username: berke
    password: pgdb-pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8040
