spring:
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8040
application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products