spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # specific predicates instead
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: basket-service
          uri: lb://BASKET-SERVICE
          predicates:
            - Path=/api/v1/baskets/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/api/v1/search/products/**
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.web.reactive: DEBUG
    io.jsonwebtoken: DEBUG
server:
  port: 8222