apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product-deployment
  labels:
    app: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres-product
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: product-postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                 secretKeyRef:
                  name: product-postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: product-postgres-config
                  key: postgres-db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product-service
spec:
  selector:
    app: postgres-product
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432