auth:
  enablePostgresUser: false
  existingSecret: "postgres-credentials"
  secretKeys:
    adminUserKey: "POSTGRES_USER"
    adminPasswordKey: "POSTGRES_PASSWORD"

primary:
  persistence:
    enabled: true
    size: 5Gi 

  initdb:
    scripts:
      init.sql: |
        CREATE DATABASE auth;
        CREATE DATABASE product;
        CREATE DATABASE payment;
        CREATE DATABASE order;