name: Config Base Build

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      java-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run tests
        run: |
          cd services/${{ inputs.service-name }}
          ./mvnw test

      - name: Run checkstyle
        run: |
          cd services/${{ inputs.service-name }}
          ./mvnw checkstyle:check

      - name: Package Application
        run: |
          cd services/${{ inputs.service-name }}
          ./mvnw package -DskipTests

      - name: Build and Push Docker Image
        run: |
          cd services/${{ inputs.service-name }}
          IMAGE_NAME="berkesayin/${{ inputs.service-name }}"
          docker build -t "$IMAGE_NAME:latest" .
          docker push "$IMAGE_NAME:latest"